web_app/routes/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from web_app.models import User
from web_app.extensions import db
from web_app.forms import LoginForm, RegisterForm, LogoutForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user, remember=True)
            return redirect(url_for('views.admin_base' if user.is_admin else 'views.user_base'))
        else:
            flash('Invalid email or incorrect password. Please try again.', category='error')
    else:
        if request.method == 'POST':
            for errors in form.errors.values():
                for error in errors:
                    flash(error, category='error')

    return render_template("login.html", user=current_user, form=form)

@auth.route('/logout', methods=['POST'])
@login_required
def logout():
    form = LogoutForm()
    if form.validate_on_submit():
        logout_user()
        flash('Logged out successfully.', category='success')
        return redirect(url_for('auth.login'))
    else:
        flash('Invalid logout attempt (CSRF token missing or invalid).', category='error')
        return redirect(url_for('views.user_base'))

@auth.route('/register', methods=['GET', 'POST'])
@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
        email = form.email.data
        first_name = form.first_name.data
        password1 = form.password1.data

        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            flash('Email already registered.', category='error')
        else:
            new_user = User(
                email=email,
                first_name=first_name,
                password=generate_password_hash(password1, method='pbkdf2:sha256')
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.user_base'))
    
    elif request.method == 'POST':
        for field_errors in form.errors.values():
            for error in field_errors:
                flash(error, category='error')

    return render_template("register.html", user=current_user, form=form)

web_app/routes/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func
from collections import defaultdict
from web_app.models import UserPlant, Plant, User, CareNote
from web_app.extensions import db
from web_app.utils.decorators import regular_user_required, admin_required
from datetime import datetime, timedelta, timezone
from web_app.forms import AddUserPlantForm, EditUserPlantForm, PlantLibraryForm, DeletePlantForm, LogoutForm

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return redirect(url_for('auth.login'))

@views.route('/navigation_base')
@login_required
def navigation_base():
    logout_form = LogoutForm()
    return render_template("navigation_base.html", logout_form=logout_form, user_name=current_user.first_name)

@views.route('/my_plants', methods=['GET', 'POST'])
@login_required
@regular_user_required
def my_plants():
    logout_form = LogoutForm()
    form = AddUserPlantForm()
    form.plant_id.choices = [(p.plant_id, p.plant_type) for p in Plant.query.all()]
    available_plants = Plant.query.all()

    if form.validate_on_submit():
        last_watered_date = form.last_watered.data
        next_watering_date = last_watered_date + timedelta(days=7)

        new_user_plant = UserPlant(
            user_id=current_user.user_id,
            plant_id=form.plant_id.data,
            plant_name=form.plant_name.data,
            last_watered=last_watered_date,
            next_watering_date=next_watering_date
        )
        db.session.add(new_user_plant)
        db.session.commit()

        if form.care_note.data:
            note = CareNote(
                user_plant_id=new_user_plant.user_plant_id,
                care_note=form.care_note.data,
                note_date=datetime.now(timezone.utc).date()
            )
            db.session.add(note)
            db.session.commit()

        flash(f"{new_user_plant.plant_name} added successfully", category="success")
        return redirect(url_for("views.my_plants"))
    elif request.method == "POST":
        flash("Please fix the errors in the form", category="error")

    user_plants = UserPlant.query.filter_by(user_id=current_user.user_id).all()
    notes_for_each_plant = defaultdict(list)
    for plant in user_plants:
        for note in plant.care_notes:
            notes_for_each_plant[plant].append(note)

    return render_template("my_plants.html", form=form, plants=user_plants,
                           total_user_plants=len(user_plants),
                           available_plants=available_plants,
                           notes_for_each_plant=notes_for_each_plant, logout_form=logout_form, user_name=current_user.first_name)

@views.route('/edit_plant', methods=['GET', 'POST'])
@login_required
@regular_user_required
def edit_plant():
    logout_form = LogoutForm()
    plant_id = request.args.get("plant_id") or request.form.get("plant_id")
    plant = UserPlant.query.get_or_404(plant_id)

    if plant.user_id != current_user.user_id:
        flash("You are not authorised to access this", category="error")
        return redirect(url_for("views.my_plants"))

    form = EditUserPlantForm(obj=plant)
    form.selected_plant_id.choices = [(p.plant_id, p.plant_type) for p in Plant.query.all()]
    form.plant_id.data = plant.user_plant_id

    if form.validate_on_submit():
        plant.plant_name = form.plant_name.data
        plant.last_watered = form.last_watered.data
        # calculation set to 7 days from when last watered
        plant.next_watering_date = plant.last_watered + timedelta(days=7)
        plant.plant_id = form.selected_plant_id.data

        if form.care_note.data:
            new_note = CareNote(
                user_plant_id=plant.user_plant_id,
                care_note=form.care_note.data,
                note_date=datetime.now(timezone.utc).date()
            )
            db.session.add(new_note)

        db.session.commit()
        flash(f"{plant.plant_name} updated successfully", category="success")
        return redirect(url_for("views.my_plants"))

    return render_template("edit_plant.html", form=form, plant=plant, logout_form=logout_form, user_name=current_user.first_name)

@views.route('/admin_base', methods=['GET'])
@login_required
@admin_required
def admin_base():
    logout_form = LogoutForm()
    users = User.query.all()
    total_users = User.query.count()
    total_user_plants = UserPlant.query.count()
    total_plants = Plant.query.count()

    plant_type_frequency = (
        db.session.query(Plant.plant_type, func.count(UserPlant.user_plant_id).label("count"))
        .outerjoin(UserPlant, Plant.plant_id == UserPlant.plant_id)
        .group_by(Plant.plant_type)
        .order_by(func.count(UserPlant.user_plant_id).desc())
        .all()
    )
    # most popular plant calculated after ordering
    if plant_type_frequency:
        most_popular_plant = plant_type_frequency[0][0]
    else:
        print("no plants")

    return render_template("admin_base.html", user=current_user, users=users, total_users=total_users, total_plants=total_plants, total_user_plants=total_user_plants, plant_type_frequency=plant_type_frequency, most_popular_plant=most_popular_plant, logout_form=logout_form, user_name=current_user.first_name)


# user home page
@views.route('/user_base')
@login_required
@regular_user_required
def user_base():
    logout_form = LogoutForm()
    return render_template("user_base.html", logout_form=logout_form, user_name=current_user.first_name)

@views.route('/plant_library', methods=['GET'])
@login_required
@regular_user_required
def plant_library():
    logout_form = LogoutForm()
    plants = Plant.query.all()
    return render_template("plant_library.html", user=current_user, plants=plants, logout_form=logout_form, user_name=current_user.first_name)


@views.route('/manage_library', methods=['GET', 'POST'])
@login_required
@admin_required
def manage_library():
    logout_form = LogoutForm()
    plants = Plant.query.all()
    form = PlantLibraryForm()

    if form.validate_on_submit():
        new_plant = Plant(
            plant_type=form.plant_type.data,
            water=form.water.data,
            light=form.light.data,
            soil=form.soil.data
        )
        db.session.add(new_plant)
        db.session.commit()

        flash(f'{new_plant.plant_type} added to the plant library', category='success')
        return redirect(url_for("views.manage_library"))

    # invalid form submitted
    elif form.is_submitted():
        for field_errors in form.errors.values():
            for error in field_errors:
                flash(error, category="error")

    return render_template("manage_library.html", user=current_user, plants=plants, form=form, logout_form=logout_form, user_name=current_user.first_name)



@views.route('/edit_plant_library', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_plant_library():
    logout_form = LogoutForm()
    plant_id = request.args.get("plant_id") or request.form.get("plant_id")

    if not plant_id:
        flash("no plant ID provided", category='error')
        return redirect(url_for("views.manage_library"))

    plant = Plant.query.get_or_404(plant_id)
    # prefilled form info
    form = PlantLibraryForm(obj=plant)

    if form.validate_on_submit():
        plant.plant_type = form.plant_type.data
        plant.water = form.water.data
        plant.light = form.light.data
        plant.soil = form.soil.data

        db.session.commit()
        flash(f"{plant.plant_type} updated successfully!", category="success")
        return redirect(url_for("views.manage_library"))

    elif form.is_submitted():
        for field_errors in form.errors.values():
            for error in field_errors:
                flash(error, category='error')

    return render_template("edit_plant_library.html", plant=plant, form=form, logout_form=logout_form, user_name=current_user.first_name)


@views.route('/delete_plant', methods=['POST'])
@login_required
@admin_required
def delete_plant():
    form = DeletePlantForm()

    if form.validate_on_submit():
        plant_id = form.plant_id.data
        plant = Plant.query.get_or_404(plant_id)

        db.session.delete(plant)
        db.session.commit()
        flash(f"'{plant.plant_type}' deleted successfully!", category="success")
    else:
        flash("Invalid deletion request", category="error")

    return redirect(url_for("views.manage_library"))

web_app/templates/admin_base.html
{% extends "navigation_base.html" %} {% block content %}
<div class="page-container">
  <h1>Admin dashboard</h1>
  <div class="mini-card-container">
    <div class="mini-card">
      <p>Total number of user accounts: {{ total_users }}</p>
    </div>
    <div class="mini-card">
      <p>Total number of user plants: {{ total_user_plants }}</p>
    </div>
    <div class="mini-card">
      <p>Total plants in library: {{ total_plants }}</p>
    </div>
    <div class="mini-card">
      <p>Most popular plant type: {{ most_popular_plant }}</p>
    </div>
  </div>

  <div class="tables-container">
    <div class="table-wrapper">
      <h3>View Users</h3>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Email</th>
              <th>Role</th>
              <th>Number of Plants</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
            <tr>
              <td>{{ user.email }}</td>
              <td>{{ 'Admin' if user.is_admin else 'User' }}</td>
              <td>{{ user.user_plants | length }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="table-wrapper">
      <h3>Frequency of Plant Type</h3>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Plant Type</th>
              <th>Number of Users Caring for this Plant Type</th>
            </tr>
          </thead>
          <tbody>
            {% for plant_type, count in plant_type_frequency %}
            <tr>
              <td>{{ plant_type }}</td>
              <td>{{ count }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Flourish{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
  </head>
  <body>
    <nav class="navbar">
      <div class="nav-left">
        <a
          href="{% if current_user.is_admin %}/admin_base{% else %}/user_base{% endif %}"
          class="app-name"
        >
          <img
            src="{{ url_for('static', filename='FlourishLogo.svg') }}"
            alt="Logo"
          />
          Flourish
        </a>
      </div>
      <div class="nav-center">{% block nav_links %}{% endblock %}</div>
      <div class="nav-right">{% block nav_icons %}{% endblock %}</div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <ul class="flashes">
      {% for category, message in messages %} {% if category == 'error' %}
      <div class="alert-danger">
        <span class="material-icons">error</span>
        {{ message }}
        <button
          type="button"
          onclick="this.parentElement.style.display='none';"
          class="close-btn"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert-success">
        <span class="material-icons">check_circle</span>
        {{ message }}
        <button
          type="button"
          onclick="this.parentElement.style.display='none';"
          class="close-btn"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <main>
      {% block header %}{% endblock %} {% block content %}{% endblock %}
    </main>

    <script>
      function toggleDropdown() {
        const dropdown = document.getElementById("user-dropdown");
        const wrapper = document.getElementById("account-wrapper");

        dropdown.classList.toggle("hidden");
        wrapper.classList.toggle("active");
      }

      document.addEventListener("click", function (e) {
        const wrapper = document.getElementById("account-wrapper");
        const dropdown = document.getElementById("user-dropdown");

        if (!wrapper.contains(e.target) && !dropdown.contains(e.target)) {
          dropdown.classList.add("hidden");
          wrapper.classList.remove("active");
        }
      });
    </script>
  </body>
</html>

web_app/templates/edit_plant.html
{% extends "navigation_base.html" %} {% block content %}
<div class="modal-page-wrapper">
  <div class="modal-content modal-centred">
    <h2>Edit Plant</h2>
    <form method="POST">
      {{ form.hidden_tag() }} {{ form.plant_id }}
      <div class="form-group">
        {{ form.plant_name.label }} {{ form.plant_name(class="form-control") }}
        {% for error in form.plant_name.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.selected_plant_id.label }} {{
        form.selected_plant_id(class="form-control") }} {% for error in
        form.selected_plant_id.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.last_watered.label }} {{ form.last_watered(class="form-control")
        }} {% for error in form.last_watered.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.care_note.label }} {{ form.care_note(class="form-control") }} {%
        for error in form.care_note.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-actions">
        {{ form.submit(class="btn-primary") }}
        <a href="{{ url_for('views.my_plants') }}" class="btn-secondary"
          >Cancel</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock %}

web_app/templates/edit_plant_library.html
{% extends "navigation_base.html" %} {% block content %}
<div class="modal-page-wrapper">
  <div class="modal-content modal-centred">
    <h2>Edit Plant Library</h2>

    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.plant_type.label }} {{ form.plant_type(class="form-control") }}
        {% for error in form.plant_type.errors %}
        <div class="alert-danger">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.water.label }} {{ form.water(class="form-control") }} {% for
        error in form.water.errors %}
        <div class="alert-danger">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.light.label }} {{ form.light(class="form-control") }} {% for
        error in form.light.errors %}
        <div class="alert-danger">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{ form.soil.label }} {{ form.soil(class="form-control") }} {% for error
        in form.soil.errors %}
        <div class="alert-danger">{{ error }}</div>
        {% endfor %}
      </div>
      <div class="form-actions">
        {{ form.submit(class="btn-primary btn-register") }}
        <a href="{{ url_for('views.manage_library') }}" class="btn-secondary">
          Cancel
        </a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

web_app/templates/login.html
{% extends "base.html" %} {% block title %}Log In{% endblock %} {% block content
%} {% if error %}
<div class="errorMessage">{{ error }}</div>
{% endif %}

<div class="center-container">
  <div class="login-card">
    <div class="login-card-header">
      <h1>Flourish</h1>
      <h2>Log in to Flourish</h2>
    </div>

    <div class="login-card-content">
      <form method="POST" class="form-container">
        {{ form.hidden_tag() }}

        <div class="form-group">
          {{ form.email(class="form-control", placeholder="Email address") }}
        </div>

        <div class="form-group">
          {{ form.password(class="form-control", placeholder="Password") }}
        </div>

        <div class="form-group">
          {{ form.submit(class="btn-primary login-btn") }}
        </div>
      </form>
    </div>

    <div class="divider-container">
      <div role="separator" class="separator">
        <hr class="solid" />
      </div>
    </div>

    <div class="create-account">
      <a
        href="{{ url_for('auth.register') }}"
        class="btn-secondary btn-register"
      >
        Create an account
      </a>
    </div>
  </div>
</div>
{% endblock %}

web_app/templates/macros.html
{% macro nav_link(href, label) %}
<a
  href="{{ href }}"
  class="nav-link {% if request.path == href %}active{% endif %}"
>
  {{ label }}
</a>
{% endmacro %} {% macro nav_svg_icon(user_name, logout_form=None) %}
<div class="account-wrapper" id="account-wrapper">
  <svg
    id="account-icon"
    onclick="toggleDropdown()"
    xmlns="http://www.w3.org/2000/svg"
    width="36"
    height="36"
    fill="currentColor"
    viewBox="0 0 24 24"
    class="nav-icon"
  >
    <title>Account</title>
    <path
      d="M12 12c2.7 0 4.9-2.2 4.9-4.9S14.7 2.2 12 2.2S7.1 4.4 7.1 7.1S9.3 12 12 12zm0 2.4
           c-3.3 0-9.8 1.7-9.8 5.1V22h19.6v-2.5c0-3.4-6.5-5.1-9.8-5.1z"
    />
  </svg>

  <div id="user-dropdown" class="user-dropdown hidden">
    <p>Hello, {{ user_name }}</p>
    {% if logout_form %}
    <form method="POST" action="{{ url_for('auth.logout') }}">
      {{ logout_form.hidden_tag() }}
      <button
        type="submit"
        class="btn-primary logout-btn"
        onclick="return confirm('{{ user_name }} are you sure you want to sign out?')"
      >
        Sign out
      </button>
    </form>
    {% endif %}
  </div>
</div>
{% endmacro %}

web_app/templates/manage_library.html
{% extends "navigation_base.html" %} {% block header %}
<div class="page-container">
  <h1>All plants</h1>
  {% endblock %} {% block content %}

  <div class="top-bar">
    <button onclick="openModal('addPlantModal')" class="btn-primary">
      Add a new plant
    </button>
  </div>

  <div id="addPlantModal" class="modal">
    <div class="modal-content">
      <span class="close" onclick="closeModal('addPlantModal')">&times;</span>
      <h2>Add a plant to library</h2>
      <form method="POST" action="{{ url_for('views.manage_library') }}">
        {{ form.hidden_tag() }}

        <div class="form-group">
          {{ form.plant_type.label }} {{ form.plant_type(class="form-control")
          }}
        </div>
        <div class="form-group">
          {{ form.water.label }} {{ form.water(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.light.label }} {{ form.light(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.soil.label }} {{ form.soil(class="form-control") }}
        </div>
        <div class="form-button-wrapper">
          {{ form.submit(class="btn-primary") }}
        </div>
      </form>
    </div>
  </div>

  <div class="plant-grid">
    {% for plant in plants %}
    <div class="plant-card">
      <div class="card-actions-top">
        <a
          href="{{ url_for('views.edit_plant_library', plant_id=plant.plant_id) }}"
          class="btn-secondary-icon"
          title="Edit"
        >
          <span class="material-icons">edit</span>
        </a>
        <form
          method="POST"
          action="{{ url_for('views.delete_plant') }}"
          style="display: inline"
        >
          <input type="hidden" name="plant_id" value="{{ plant.plant_id }}" />
          <button
            class="btn-danger-icon"
            type="submit"
            onclick="return confirm('Are you sure you want to delete {{plant.plant_type}} from the plant library? This action cannot be reversed.')"
            title="Delete"
          >
            <span class="material-icons">delete</span>
          </button>
        </form>
      </div>
      <img
        src="{{ url_for('static', filename='plant_images/' + (plant.image_filename or 'placeholder.png')) }}"
        alt="{{ plant.plant_name }}"
        class="card-img"
      />
      <div class="card-content">
        <h3>{{ plant.plant_type }}</h3>
        <p>Water: {{ plant.water }}</p>
        <p>Light: {{ plant.light }}</p>
        <p>Soil: {{ plant.soil }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<script>
  function openModal(id) {
    document.getElementById(id).style.display = "flex";
  }

  function closeModal(id) {
    document.getElementById(id).style.display = "none";
  }
</script>

{% endblock %}

web_app/templates/my_plants.html
{% extends "navigation_base.html" %} 
  {% block header %}
  <div class="page-container">
  <h1>{{ current_user.first_name }}'s Plant Dashboard</h1>
  {% endblock %} {% block content %}
    <div class="mini-card" style="width: 20px">
      <p>Total plants: {{ total_user_plants }}</p>
    </div>

    <div id="addPlantModal" class="modal">
      <div class="modal-content">
        <span class="close" onclick="closeModal('addPlantModal')">&times;</span>
        <form method="POST" action="{{ url_for('views.my_plants') }}">
        {{ form.hidden_tag() }}
        <h2>Add a plant</h2>

        <div class="form-group">
          {{ form.plant_name.label }}
          {{ form.plant_name(class="form-control") }}
          {% for error in form.plant_name.errors %}
            <div class="form-error">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="form-group">
          {{ form.plant_id.label }}
          {{ form.plant_id(class="form-control") }}
          {% for error in form.plant_id.errors %}
            <div class="form-error">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="form-group">
          {{ form.last_watered.label }}
          {{ form.last_watered(class="form-control") }}
          {% for error in form.last_watered.errors %}
            <div class="form-error">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="form-group">
          {{ form.care_note.label }}
          {{ form.care_note(class="form-control") }}
          {% for error in form.care_note.errors %}
            <div class="form-error">{{ error }}</div>
          {% endfor %}
        </div>

        <div class="form-button-wrapper">
          {{ form.submit(class="btn-primary btn-register") }}
        </div>
      </form>
      </div>
    </div>
    <div class="user-plant-details">
      <h3>Your plant care details</h3>
      <button onclick="openModal('addPlantModal')" class="btn-primary add-btn">
        Add a new plant
      </button>
    </div>
    <div class="table-container">
      <table class="my-plants-table">
        <thead>
          <tr>
            <th>Plant Type</th>
            <th>Plant Name</th>
            <th>Last Watered</th>
            <th>Next Watering Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for plant in plants %}
          <tr>
            <td>{{ plant.plant.plant_type }}</td>
            <td>{{ plant.plant_name }}</td>
            <td>{{ plant.last_watered }}</td>
            <td>{{ plant.next_watering_date }}</td>
            <td>
              <form method="GET" action="{{ url_for('views.edit_plant') }}">
                <input
                  type="hidden"
                  name="plant_id"
                  value="{{ plant.user_plant_id }}"
                />
                <button type="submit" class="btn-secondary-icon" title="Edit">
                  <span class="material-icons">edit</span>
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="table-container">
  <table class="my-plants-table">
    <thead>
      <tr>
        <th>Plant Name</th>
        <th>All Plant Notes</th>
      </tr>
    </thead>
    <tbody>
      {% for plant, care_notes in notes_for_each_plant.items() %}
      <tr>
        <td>{{ plant.plant_name }}</td>
        <td>
          {% if care_notes %}
            <ul>
              {% for note in care_notes %}
                <li>{{ note.care_note }} ({{ note.note_date }})</li>
              {% endfor %}
            </ul>
          {% else %}
            <p>No notes yet</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  </div>
</div>
<script>
  function openModal(id) {
    document.getElementById(id).style.display = "flex";
  }

  function closeModal(id) {
    document.getElementById(id).style.display = "none";
  }
</script>
{% endblock %}

web_app/templates/navigation_base.html
{% extends "base.html" %} {% import "macros.html" as ui %} {% block nav_links %}
{% if current_user.is_admin %} {{ ui.nav_link('/admin_base', 'Admin Dashboard')
}} {{ ui.nav_link('/manage_library', 'Manage Plant Library') }} {% else %} {{
ui.nav_link('/my_plants', 'My Plants') }} {{ ui.nav_link('/plant_library',
'Plant Library') }} {% endif %} {% endblock %} {% block nav_icons %} {{
ui.nav_svg_icon(current_user.first_name or current_user.email, logout_form) }}
{% endblock %}

web_app/templates/user_base.html
{% extends "navigation_base.html" %} {% block content %}
<div class="homepage-grid">
  <div class="tile top-left">
    <div class="tile-info">
      <h1>Flourish and Thrive</h1>
      <h2>Track your plant care</h2>
      <a href="{{ url_for('views.my_plants') }}" class="btn-primary">
        View your plant dashboard
        <span class="material-icons">arrow_forward</span>
      </a>
    </div>
  </div>
  <div class="tile top-right">
    <img
      src="{{ url_for('static', filename='home_images/plant.png') }}"
      alt="Plant illustration"
      class="tile-img"
    />
  </div>
  <div class="tile bottom-left">
    <img
      src="{{ url_for('static', filename='home_images/flowers.png') }}"
      alt="Flower illustration"
      class="tile-img"
    />
  </div>
  <div class="tile bottom-right">
    <div class="tile-info">
      <h1>Explore plant varieties</h1>
      <h2>Improve your knowledge and learn to care for your plants</h2>
      <a href="{{ url_for('views.plant_library') }}" class="btn-primary"
        >View plant library
        <span class="material-icons">arrow_forward</span>
      </a>
    </div>
  </div>
</div>
{% endblock %}